-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
-- if vim.lsp.inlay_hint then
--  vim.lsp.inlay_hint.enable(0, true)
-- end
